# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PJMFl2a_nZiWNJyoZymFRarDMwiuzo7K
"""

# You should save the code below into a file named 'app.py' and run it from your terminal
# using the command: streamlit run app.py

# app.py (Save this code into a file named app.py)
import streamlit as st
import pandas as pd
import numpy as np
import tensorflow as tf
import joblib

# Load model dan scaler
# Ensure 'toyota_ann_model.h5' and 'scaler.pkl' are in the same directory as app.py
model = tf.keras.models.load_model('toyota_ann_model.h5', compile=False)
model.compile(optimizer='adam', loss='mse', metrics=['mae'])
scaler = joblib.load('scaler.pkl')

EUR_TO_IDR = 18617.72

# Streamlit UI components
# It's better to import streamlit only once at the beginning
# import streamlit as st # This line is redundant if already imported above
st.image("https://drive.google.com/file/d/1L8df0VxJWKNK3GfxaeDPbNRnl-70I3Ge/view?usp=sharing", use_column_width=True)
st.markdown("**Prediksi Harga Mobil Toyota Bekas Anda Dalam Hitungan Detik**")

# Input user
year = st.number_input("Tahun Mobil", 1990, 2025, 2018)
mileage = st.number_input("Jarak Tempuh (km)", 0, 300000, 50000)
tax = st.number_input("Pajak (Euro)", 0, 600, 150)
mpg = st.number_input("Konsumsi BBM (mpg)", 10.0, 100.0, 40.0)
engineSize = st.number_input("Ukuran Mesin (liter)", 0.5, 6.0, 1.6, 0.1)

if st.button("Prediksi Harga"):
    input_df = pd.DataFrame([[year, mileage, tax, mpg, engineSize]],
                            columns=['year', 'mileage', 'tax', 'mpg', 'engineSize'])
    input_scaled = scaler.transform(input_df)
    # model.predict returns a numpy array, access the scalar value
    prediction_euro = model.predict(input_scaled)[0][0]
    prediction_rupiah = prediction_euro * EUR_TO_IDR
    tax_rupiah = tax * EUR_TO_IDR

    st.markdown(f"💶 Pajak Mobil: Rp {tax_rupiah:,.2f}")
    st.success(f"💰 Estimasi Harga Mobil Bekas: Rp {prediction_rupiah:,.2f}")

# After saving the code above as 'app.py', open your terminal, navigate to the directory where you saved it, and run:
# streamlit run app.py
